from setuptools import setup


setup(
    name='ldaplog',
    version='1.2',
    url='https://github.com/eea/ldaplog',
    license='Mozilla Public License',
    author='Eau de Web',
    author_email='office@eaudeweb.ro',
    description='LDAP event monitor',
    packages=['ldaplog'],
    include_package_data=True,
    zip_safe=False,
    platforms='any',
    install_requires=[
        'MySQL-python',
        'raven',
        'SQLAlchemy',
        'Flask',
        'Jinja2',
        'Werkzeug',
        'Flask-Script',
        'python-dateutil',
        'pytz',
        'six',
        'times',
        'Flask-Admin',
        'Flask-WTF',
        'WTForms',
        'python-ldap',
        'simplejson',
        'tornado',
    ],
    entry_points = {'console_scripts': ['manage = ldaplog.manage:main']},
    classifiers=[
        'Development Status :: 4 - Beta',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
        'Topic :: Software Development :: Libraries :: Python Modules'
    ],
)
